repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        sudo docker run --platform linux/amd64 -it -v "$PWD:/pwd" trufflesecurity/trufflehog:latest git https://github.com/sudo-abhish3k/juice-shop
        language: system
        stages: ["commit", "push"]
